#!/usr/bin/env ruby

#
# brew install ghostscript
#

require 'RMagick'
require 'colorize'

def fit(file)
  file
    .gsub("(", "_")
    .gsub(")", "_")
    .gsub("（", "_")
    .gsub("）", "_")
    .gsub(" ", "")
end

def make_file(file_name)
  return "file doesn't exist : #{file_name}\n" unless File.exist?(file_name)
  return "" unless file_name.end_with?(".pdf")

  package = fit(File.basename(file_name).split(".")[0]) + "_jp"
  system "mkdir -p #{package}"

  image = Magick::Image.read(file_name){
    self.size = "200x"
    self.quality = 100
    self.density = 200
  }

  if image.size > 0
    image.each_with_index do |page, p|
      page = page.opaque('#CCCCCC00', "#CCCCCC00")
      page.write(package + "/#{p}.jpg")
      print "in progress: [#{p+1}/#{image.size}]         \r"
    end  
    #system "open #{package}"
  else
     return "image reading failure with #{file_name}\n"
  end
  puts "SUCCESS #{file_name}".green
  return ""
rescue
  return "ERROR #{file_name}\n"
end  

def options
  ARGV.select{|arg| arg.start_with?("-") }
end

def args
  ARGV.select{|arg| !arg.start_with?("-") }
end

if ARGV.size == 0
  abort "\nyou need file/dir name as argument\n\n"
end

asterisk = "*"


case options.first
when "-h", "--help"
  puts 
  puts "pdfuck -h             ... help menu"
  puts "pdfuck -r [directory] ... recursively convert pdf to jpegs"
  puts "pdfuck [file]         ... convert pdf to jpegs"
  puts "pdfuck -c [dir]       ... combine jpegs into one"
  puts 
when "-c"
  files = Dir["#{args.first}/*"].map do |file|
    new_path = File.join(File.dirname(file), File.basename(file).rjust(14, "0"))
    system "mv #{file} #{new_path}"
    new_path
  end
 
  files = files.sort

  puts "=================".cyan
  puts files
  puts "=================".cyan
  system "convert -append " + files.join(" ") +  " aaa.jpg"
  puts "done!"
else 
  if ARGV.include?("-r")
    asterisk = "**/*"
  end

  args.each do |file_name|
    if File.directory?(file_name)
      Dir["#{file_name}/#{asterisk}"].each do |file|
        print make_file(file).red
      end
    else
      print make_file(file_name).red
    end
  end  
end


